---
- hosts: all
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Update apt cache if necessary
      apt: update_cache=true cache_valid_time=3600

  roles:
    - role: bootstrap
      tags: ["bootstrap"]

    - role: nspawn-container
      vars:
        hostname: "web"
        port_forwards:
          - "tcp:8000:8000"
      tags: ["web"]
