---
- hosts: all
  gather_facts: yes
  become: yes

  vars:
    pip_package: python3-pip
    pip_install_packages:
      - docker

  roles:
    - role: common
      tags: ['common']

    - role: users
      tags: ['users']
      
    - role: geerlingguy.pip
      tags: ['pip']

    - role: geerlingguy.docker
      tags: ['docker']
