---
- name: Install python3-apt package to manage apt
  command: |
    sudo apt-get update -y
    sudo apt-get install python3-apt
  args:
    creates: '/usr/share/doc/python3-apt'

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Allow passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regex: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
