---
- name: Install python3-apt package to manage apt
  command: |
    sudo apt-get update -y
    sudo apt-get install python3-apt
  args:
    creates: '/usr/share/doc/python3-apt'

- name: Update apt and upgrade
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Allow passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regex: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Disable passwordless ssh authentication
  lineinefile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
